### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by the-maldridge** [MiLk/nsscache-go#7]
I'd like to use this library to replace the hacky string processing in [NetAuth/nsscache](https://github.com/NetAuth/nsscache), but to do that, I'd feel much comfortable if I could lock to a particular release of this library.  Would you consider releasing 0.1 to facilitate this?

**Comment by MiLk** [comment]
This has been running in production for a long time now, so I've tagged it `v1.0.0`.
https://github.com/MiLk/nsscache-go/releases/tag/v1.0.0

**Comment by the-maldridge** [comment]
Thanks!
